Repository lsst-it/k8s-cookbook, pull requests merged in 2024-04, with the labels that each got.

#300 (fleet/kube-prometheus-stack) add puppetdb sd for node exporter
  fleet/lib/kube-prometheus-stack/overlays/pillan/values.yaml
  fleet/lib/kube-prometheus-stack/overlays/ruka/values.yaml
Labels: enhancement

#301 (fleet/multus) mv network-attachment-definition-* -> net-attach-def-*
  fleet/lib/multus-conf/overlays/konkong/net-attach-def-lhn.yaml
  fleet/lib/multus-conf/overlays/kueyen/net-attach-def-dds.yaml
  fleet/lib/multus-conf/overlays/manke/net-attach-def-dds.yaml
  fleet/lib/multus-conf/overlays/manke/net-attach-def-lhn.yaml
  fleet/lib/multus-conf/overlays/pillan/net-attach-def-dds.yaml
  fleet/lib/multus-conf/overlays/pillan/net-attach-def-misc-dds.yaml
  fleet/lib/multus-conf/overlays/ruka/net-attach-def-lhn.yaml
Labels: bug

#299 (manke) add htcondor deployment
  fleet/lib/metallb-conf/overlays/manke/ipaddresspool-htcondor.yaml
  fleet/lib/multus-conf/overlays/manke/net-attach-def-htcondor.yaml
  manke/htcondor/externalsecret-htcondor-pool-password.yaml
  manke/htcondor/htcondor-central-manager-deployment.yaml
  manke/htcondor/htcondor-central-manager-service.yaml
  manke/htcondor/htcondor-worker-deployment.yaml
  manke/htcondor/htcondor.sh
Labels: enhancement

#303 (rancher.dev) bump rancher to 2.8.3
  rancher.dev/rancher/rancher.sh
Labels: enhancement

#305 (pillan) mv cnpg to fleet
  fleet/lib/cnpg-cluster/fleet.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/cluster-cnpg-cluster.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/externalsecret-cnpg-aws-creds.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/externalsecret-cnpg-cluster-superuser.yaml
  fleet/lib/cnpg-cluster/overlays/ruka/cluster-cnpg-cluster.yaml
  fleet/lib/cnpg-cluster/overlays/ruka/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/ruka/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/ruka/externalsecret-cnpg-aws-creds.yaml
  fleet/lib/cnpg-cluster/overlays/ruka/externalsecret-cnpg-cluster-superuser.yaml
  fleet/s/tu/c/pillan/cnpg-cluster
  fleet/s/tu/c/pillan/cnpg-system
  pillan/cnpg/.gitignore
  pillan/cnpg/README.md
  pillan/cnpg/cnpg-backup.sh
  pillan/cnpg/cnpg.sh
Labels: enhancement

#306 (pillan) fleet cnpg typo fix
  fleet/lib/cnpg-system/fleet.yaml
Labels: bug

#292 (gha) add helm chart lint
  .github/workflows/chart-lint.yaml
  utils/chart-lint.go
Labels: enhancement

#315 (fleet/multus) increase request to 64Mi; limit to 128Mi
  fleet/lib/multus/multus-daemonset-thick.yml
Labels: bug

#314 (cnpg) manke cnpg to fleet
  fleet/lib/cnpg-cluster/fleet.yaml
  fleet/lib/cnpg-cluster/overlays/manke/cluster-cnpg-cluster.yaml
  fleet/lib/cnpg-cluster/overlays/manke/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/manke/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/manke/externalsecret-cnpg-aws-creds.yaml
  fleet/lib/cnpg-cluster/overlays/manke/externalsecret-cnpg-cluster-superuser.yaml
  fleet/s/ls/c/manke/cnpg-cluster
  fleet/s/ls/c/manke/cnpg-system
  manke/cnpg/README.md
  manke/cnpg/cnpg-backup.sh
  manke/cnpg/cnpg.sh
Labels: enhancement

#309 (rancher.cp) update node names: rancherX -> rancher0X
  rancher.cp/rke/cluster.yml
Labels: enhancement

#316 (rancher.*) bump rancher to 2.8.3
  rancher.cp/rancher/rancher.sh
  rancher.ls/rancher/rancher.sh
  rancher.tu/rancher/rancher.sh
Labels: enhancement

#318 (yagan,yepun) bump k8s to 1.25.9-rancher2-2
  yagan/rke/cluster.yml
  yepun/rke/cluster.yml
Labels: enhancement

#313 (cnpg) yepun and yagan into fleet
  fleet/lib/cnpg-cluster/fleet.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/cluster-cnpg-cluster.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/cnpg-loadBalancer-lhn.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/externalsecret-cnpg-aws-creds.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/externalsecret-cnpg-cluster-superuser.yaml
  fleet/lib/cnpg-cluster/overlays/yepun/cluster-cnpg-cluster.yaml
  fleet/lib/cnpg-cluster/overlays/yepun/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/yepun/externalsecret-cnpg-cluster-superuser.yaml
  fleet/s/cp/c/yagan/cnpg-cluster
  fleet/s/cp/c/yagan/cnpg-system
  fleet/s/cp/c/yepun/cnpg-cluster
  fleet/s/cp/c/yepun/cnpg-system
  yagan/cnpg/README.md
  yagan/cnpg/cnpg-backup.sh
  yagan/cnpg/cnpg.sh
  yepun/cnpg/README.md
  yepun/cnpg/cnpg-backup.sh
  yepun/cnpg/cnpg.sh
Labels: enhancement

#319 (yagan) fix net-attach-def's to use bridge interfaces
  fleet/lib/multus-conf/overlays/yagan/net-attach-def-dds.yaml
  fleet/lib/multus-conf/overlays/yagan/net-attach-def-macvlan-conf.yaml
Labels: bug

#320 (fleet/cnpg-system) increase mem to 192Mi/384Mi
  fleet/lib/cnpg-system/fleet.yaml
Labels: bug

#321 (ruka,yagan,yepun) do not enable svc nodeports
  fleet/lib/cnpg-cluster/overlays/ruka/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/cnpg-loadBalancer-lhn.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/yepun/cnpg-loadBalancer.yaml
Labels: bug

#322 (pillan,manke) do not enable svc nodeports
  fleet/lib/cnpg-cluster/overlays/manke/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/cnpg-loadBalancer.yaml
Labels: bug

#298 (fleet/velero) bump chart to 5.4.1
  fleet/lib/velero/fleet.yaml
Labels: bug

#323 (dev/*) bump k8s to v1.27.12-rancher1-1
  ayekan/rke/cluster.yml
  kueyen/rke/cluster.yml
  namkueyen/rke/cluster.yaml
  rancher.dev/rancher/values.yaml
  rancher.dev/rke/cluster.yml
  ruka/rke/cluster.yml
Labels: enhancement

#324 (fleet/cnpg-cluster) remove yepun & bump v0.5
  fleet/lib/cnpg-cluster/fleet.yaml
  fleet/lib/cnpg-cluster/overlays/manke/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/ruka/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/cnpg-backup.yaml
  fleet/lib/cnpg-cluster/overlays/yepun/cluster-cnpg-cluster.yaml
  fleet/lib/cnpg-cluster/overlays/yepun/cnpg-loadBalancer.yaml
  fleet/lib/cnpg-cluster/overlays/yepun/externalsecret-cnpg-cluster-superuser.yaml
Labels: bug, enhancement

#312 (ayekan) rm manual exporter deploys which have already been migrated to fleet
  ayekan/exporters/blackbox-exporter/helm-values.yaml
  ayekan/exporters/deploy-exporters.sh
  ayekan/exporters/deploy-target-configmap.sh
  ayekan/exporters/snmp-exporter/configmap.yaml
  ayekan/exporters/snmp-exporter/externalsecret.yaml
  ayekan/exporters/snmp-exporter/helm-values.yaml
  ayekan/exporters/snmp-exporter/schneider-configmap.yaml
  ayekan/exporters/snmp-exporter/xups-configmap.yaml
  ayekan/prometheus/prometheus.sh
  ayekan/prometheus/values.yaml
  ayekan/prometheus/webhooks-secret.yaml
  fleet/lib/kube-prometheus-stack/aggregator/values.yaml
Labels: enhancement

#307 (ayekan) enable puppetdb http basic auth + use enc data as labels
  fleet/lib/kube-prometheus-stack/overlays/ayekan/values.yaml
Labels: enhancement

#308 (ayekan) update snmp cms to match kube-prometheus-stack-pre
  fleet/lib/kube-prometheus-stack/overlays/ayekan/values.yaml
Labels: bug

#310 s/keycloack/keycloak/
  fleet/lib/kube-prometheus-stack-pre/externalsecret-grafana-keycloak-credentials.yaml
  fleet/lib/kube-prometheus-stack/aggregator/values.yaml
  fleet/lib/opensearch-logging/clusters/logging-configmap.yaml
  fleet/lib/opensearch-logging/clusters/logging-externalsecrets.yaml
  fleet/lib/opensearch-logging/clusters/logging.yaml
Labels: bug

#326 (fleet/cnpg-cluster) rm external-secret-cnpg-aws-creds -- unused
  fleet/lib/cnpg-cluster/overlays/manke/externalsecret-cnpg-aws-creds.yaml
  fleet/lib/cnpg-cluster/overlays/pillan/externalsecret-cnpg-aws-creds.yaml
  fleet/lib/cnpg-cluster/overlays/ruka/externalsecret-cnpg-aws-creds.yaml
  fleet/lib/cnpg-cluster/overlays/yagan/externalsecret-cnpg-aws-creds.yaml
Labels: bug

#327 (ayekan) reduce replicapool quota to 1.5TiB
  fleet/lib/rook-ceph-cluster/overlays/ayekan/values.yaml
Labels: bug

#328 (fleet/rook-ceph-cluster) enable modern ceph rbd features + discard flag
  fleet/lib/rook-ceph-cluster/overlays/ayekan/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/gaw/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/kueyen/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/luan/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/lukay/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/manke/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/namkueyen/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/pillan/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/ruka/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/yagan/values.yaml
  fleet/lib/rook-ceph-cluster/overlays/yepun/values.yaml
Labels: enhancement

#330 (ruka) add keycloak
  fleet/lib/keycloak-pg/cluster-keycloak-pg.yaml
  fleet/lib/keycloak-pg/cronjob-keycloak-pg-backup.yaml
  fleet/lib/keycloak-pg/externalsecret-keycloak-pg.yaml
  fleet/lib/keycloak-pg/fleet.yaml
  fleet/lib/keycloak-pg/overlays/ruka/externalsecret-keycloak-pg-backup.yaml
  fleet/lib/keycloak-pg/overlays/ruka/externalsecret-keycloak-pg-superuser.yaml
  fleet/lib/keycloak-pg/overlays/ruka/service-keycloak-pg.yaml
  fleet/lib/keycloak-pre/externalsecret-keycloak-admin.yaml
  fleet/lib/keycloak-pre/externalsecret-keycloak-pg.yaml
  fleet/lib/keycloak-pre/fleet.yaml
  fleet/lib/keycloak/fleet.yaml
  fleet/lib/keycloak/overlays/manke/values.yaml
  fleet/lib/keycloak/overlays/pillan/values.yaml
  fleet/lib/keycloak/overlays/yagan/values.yaml
  fleet/lib/keycloak/values.yaml
  fleet/lib/kube-prometheus-stack/overlays/ruka/values.yaml
  fleet/s/dev/c/ruka/keycloak
  fleet/s/dev/c/ruka/keycloak-pg
  fleet/s/dev/c/ruka/keycloak-pre
Labels: enhancement

#332 (fleet/cert-manager) bump chart to v1.12.9
  fleet/lib/cert-manager/fleet.yaml
Labels: enhancement

#333 (fleet/ingress-nginx{-lhn}) bump chart to v4.10.0
  fleet/lib/ingress-nginx-lhn/fleet.yaml
  fleet/lib/ingress-nginx/fleet.yaml
Labels: enhancement

#329 (fleet/kube-prometheus-stack) bump to 56.21.4
  fleet/lib/kube-prometheus-stack/fleet.yaml
Labels: enhancement

#331 (fleet/blackbox-exporter) fix ing host & tls secret name
  fleet/lib/blackbox-exporter/values.yaml
Labels: bug
